# Generated by Django 6.0.3 on 2026-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_starting_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
